### ISSUE TITLE
Be more verbose on error

### ISSUE THREAD

**Issue by davidk2-kentico** [KenticoDocs/WatsonTTS_UI#1]
Currently, when an error occurs, you only tell me that "Error occurred during synthetization. One or more errors occurred." That's not really helpful, I need to run our CLI tool for Watson TTS which includes `from ibm_watson import ApiException`. Thanks to that, I got informed that 

	ibm_cloud_sdk_core.api_exception.ApiException: Error: Input contains unsupported IPA character 0X000000E4, Code: 400 , X-global-transaction-id: c17a112d-0b74-48b7-aeea-7539fd7f9309
	Method failed with status code 400: Input contains unsupported IPA character 0X000000E4``` 
	
which actually helps.

**Comment by tomnosek** [comment]
Fixed in commit: https://github.com/KenticoDocs/WatsonTTS_UI/commit/1021542f09279ef5d12f12bf30ac7a9e31817840
